# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # AWSCLIのインストール
      - pwd
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ls -l /root/.pyenv/shims/aws
      - ./aws/install --bin-dir /root/.pyenv/shims --install-dir /usr/local/aws-cli --update
      # # Cloudwatch Agentのインストール
      # - yum install amazon-cloudwatch-agent
      # # CodeDeploy Agentのインストール
      # - yum -y install ruby
      # - yum -y install wget
      # - wget https://aws-codedeploy-ap-northeast-1.s3.amazonaws.com/latest/install; 
      # - chmod +x ./install
      # - ./install auto
      # npmのインストール
      - cd frontend
      - npm install
      - npm install -g forever
  pre_build:
    commands:
      # - sudo apt-get update && sudo apt-get install apt-transport-https
      # - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      # - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/npm.list
      # - sudo apt-get update && sudo apt-get install npm
      - npm --version
      # - npm test
  build:
    commands:
      - npm run build
      
  post_build:
    commands:
      - zip -j frontend.zip *.js *.json -r node_modules -q
      - aws s3 cp frontend.zip s3://flask-frontend
# artifacts:
#   type: zip
#   files: frontend.zip
    